### ISSUE TITLE
Varnish 4.0 support

### ISSUE THREAD

**Issue by comotion** [comotion/VSF#9]
VSF needs to work on Varnish 4.0. Port the VCL first, then the vmods.

**Comment by comotion** [comment]
Thanks to @fgsch for looking into it.

**Comment by intelbg** [comment]
Can you please give detailed steps, because following these on the page doesn't work to me (maybe I am wrong somewhere but can't understand where). I will be thankful!

**Comment by blindpet** [comment]
Looking forward to this, following for updates

**Comment by intelbg** [comment]
Ok, lets I summarize what exactly are all my problems, for which I write on five + different places and nobody can't help, but I really need this so I hope here the creator can help me and tell me what is wrong and why it doesn't work. I am pretty sure that the documentation is not full or wrong.


1. I tryed to install the vsf vmod on varnish 3 and 4 - neither of them worked. Here is the problem on version 3.  If varnish-libs and varnish-libs-devel are not installed it will print the following error:

    make[1]: Entering directory `/root/tmp/varnish-3.0.3/VSF/libvmod-urlcode’
    Making all in src
    make[2]: Entering directory `/root/tmp/varnish-3.0.3/VSF/libvmod-urlcode/src’
    make[2]: *** No rule to make target `@VMODTOOL@’, needed by `vcc_if.c’. Stop.
    make[2]: Leaving directory `/root/tmp/varnish-3.0.3/VSF/libvmod-urlcode/src’
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/root/tmp/varnish-3.0.3/VSF/libvmod-urlcode’
    make: *** [all] Error 2
    Making install in src
    make[1]: Entering directory `/root/tmp/varnish-3.0.3/VSF/libvmod-urlcode/src’
    make[1]: *** No rule to make target `@VMODTOOL@’, needed by `vcc_if.c’. Stop.
    make[1]: Leaving directory `/root/tmp/varnish-3.0.3/VSF/libvmod-urlcode/src’
    make: *** [install-recursive] Error 1

    I installed them but it didn’t work again on version 3.03 (on 4 it works). How can I fix this?

    Also the end print this error:

    libtool: Version mismatch error. This is libtool 2.4.2 Debian-2.4.2-1ubuntu1, but the
    libtool: definition of this LT_INIT comes from libtool 2.2.6b.
    libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1ubuntu1
    libtool: and run autoconf again.
    make[1]: *** [vcc_if.lo] Error 63
    make[1]: Leaving directory `/root/tmp/varnish-3.0.3/VSF/libvmod-throttle/src’
    make: *** [install-recursive] Error 1

    Which version of libtool is needed?

On version 4 I don't know even which is the branch for 4, I don't see where this is documented. Can you please post the installation steps step by stem and every dependencie to work this, where the 4 branch is and so on. I will be really thankfull, but I am sure that and the others that have the same problems (my experience shows that I am not the once), Thank you in advance!

**Comment by fgsch** [comment]
@intelbg the master branch follows Varnish Cache 4.0, the 3.0 branch Varnish Cache 3.0.
Varnish Cache 4.0 support is work in progress.

If you have problems compiling the modules with Varnish Cache 3.0 please post the full details (all typed commands, etc) in a new issue. This issue here is for 4.0 support.

**Comment by intelbg** [comment]
@fgsch The erros is the same. Here I post the stems I follow and the errors I see for varnish 4 :

history of commands:

  1  cd /usr/local/src
    2  wget http://repo.varnish-cache.org/source/varnish-4.0.3.tar.gz
    3  tar xvvf varnish-4.0.3.tar.gz 
    4  rm varnish-4.0.3.tar.gz 
    6   yum install python-docutils   libedit-devel libedit libtool make gcc gc++ make automake git
    8  cd varnish-4.0.3/
   10  ./configure 
   11  make -j3
   12  make install
   13   git clone https://github.com/comotion/VSF.git && cd - 
   14  git clone https://github.com/fastly/libvmod-urlcode.git
   15  git clone https://github.com/nand2/libvmod-throttle.git
   16  git clone https://github.com/xcir/libvmod-parsereq.git
   17  git clone https://github.com/varnish/libvmod-shield.git
   19  git clone https://github.com/fastly/libvmod-urlcode.git
   20  git clone https://github.com/nand2/libvmod-throttle.git
   21  git clone https://github.com/xcir/libvmod-parsereq.git
   22  git clone https://github.com/varnish/libvmod-shield.git
   23  for mod in parsereq urlcode shield throttle; do cd libvmod-$mod; ./autogen.sh && VARNISHSRC=/usr/local/src/varnish-4.0.3 VMODDIR=/usr/lib64/varnish/vmods ./configure && make -j3; make install; cd -; done

Ant the errors are the following:

1.  /usr/local/src/varnish-4.0.3 is not a source directory ## why as the varnish is compiled from there?

2. make[2]: Entering directory `/usr/local/src/VSF/libvmod-urlcode/src'
make[2]: *** No rule to make target `@VMODTOOL@', needed by `vcc_if.c'.  Stop.
make[2]: Leaving directory `/usr/local/src/VSF/libvmod-urlcode/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/VSF/libvmod-urlcode'
make: *** [all] Error 2
Making install in src
make[1]: Entering directory `/usr/local/src/VSF/libvmod-urlcode/src'
make[1]: *** No rule to make target `@VMODTOOL@', needed by `vcc_if.c'.  Stop.
make[1]: Leaving directory `/usr/local/src/VSF/libvmod-urlcode/src'
make: *** [install-recursive] Error 1
/usr/local/src/VSF

This error appears even if varnish-libs-devel is installed ## why and how to fix this?

**Comment by fgsch** [comment]
@intelbg As I said Varnish 4.0 support is work in progress so it's not working at the moment.

If anything provide the output for this on 3.0 and please use a separate ticket.

**Comment by intelbg** [comment]
@fgsch ok, so there is a version that even can't be installed? :) I posted another theme only for version 3 as you wanted. I would be very thankful if you help me, baucase I should finish the project tomorrow :S Here is the post:

https://github.com/comotion/VSF/issues/10

I will be waiting your reply. I provided full history and the error (I also mentioned them above early)

**Comment by fgsch** [comment]
I just committed the initial libvmod-vsf and VCL changes required for V4. Work will continue in the tree.

Please note that this relies on PRIV_TASK, a feature available only in master at the moment.
This should be included in the upcoming 4.1 release.

I will close this now. If there are any specific issues we should address them in a separate ticket.

**Comment by blindpet** [comment]
Just a quick question @fgsch does that mean it is pointless to run vsf on Varnish 4 because of the missing PRIV_TASK feature?

**Comment by comotion** [comment]
@blindpet no, you'll still get something out of it. But Varnish 4.1-beta1 just released so you can go try it out already..

**Comment by blindpet** [comment]
I guess my question is what functionality is limited without the PRIV_TASK feature?

**Comment by fgsch** [comment]
@blindpet basically without PRIV_TASK you cannot access the body, or to be more precise, you could but you will leak the memory used for it.
